### ISSUE TITLE
IllegalArgumentException on (pick :some_attribute_name) in [clojureql "1.0.4"]

### ISSUE THREAD

**Issue by jcmincke** [LauJensen/clojureql#137]
When doing a query that returns just one row, if I use 
(pick :some_attribute_name), 

I get the following exception/

IllegalArgumentException Don't know how to create ISeq from: "attribute_type"

However if I use
    (pick [:some_attribute_name])

Everything is fine.

**Comment by LauJensen** [comment]
Fixed in MASTER
