### ISSUE TITLE
Doesn't work with Clojure 1.9.0

### ISSUE THREAD

**Issue by alexott** [LauJensen/clojureql#146]
Clojure 1.9.0 is more strict with namespaced keywords, so current version doesn't compile with it because of use of `::clojureql.internal/default-connection` in code. Fix is simple - just use `:clojureql.internal/default-connection` instead.

This problem prevents from releasing Incanter with support for Clojure 1.9.0...

**Comment by LauJensen** [comment]
Thanks for the heads up! Ive pushed a new version which uses 1.9.0

**Comment by alexott** [comment]
Thank you!

**Comment by alexott** [comment]
Can you push it to Clojars? Thanks

**Comment by LauJensen** [comment]
Still waiting for the password reset mail from Clojars, but as soon as I get it, I will.

**Comment by LauJensen** [comment]
Version 1.0.5 is on Clojars now. Will do a more thorough update soon.

**Comment by alexott** [comment]
Thank you! It's downloading now
